package datapro.eibs.beans;

import java.math.BigDecimal;
import java.util.Hashtable;

import datapro.eibs.sockets.CharacterField;
import datapro.eibs.sockets.DecimalField;
import datapro.eibs.sockets.MessageField;
import datapro.eibs.sockets.MessageRecord;

/**
* class generated by AS/400 CRTCLASS command from CRF000201 physical file definition.
* 
* File level identifier is 1090121160602.
* Record format level identifier is 358D2799D05E0.
*/

/**
 * Bean para registro de cliente en IBS
 */
public class CRF000201Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E1CTEGPO",
                                     "E1CLIENTE",
                                     "E1CUENTA",
                                     "E1APEPAT",
                                     "E1APEMAT",
                                     "E1NOMBRE",
                                     "E1NOMBRE2",
                                     "E1MESNAC",
                                     "E1DIANAC",
                                     "E1ANONAC",
                                     "E1CALLE",
                                     "E1COLONIA",
                                     "E1CODCIUD",
                                     "E1CODPAIS",
                                     "E1CODESTA",
                                     "E1CODCOL",
                                     "E1POBLAC",
                                     "E1ESTADO",
                                     "E1PAIS",
                                     "E1SEXO",
                                     "E1EDOCIV",
                                     "E1RFC",
                                     "E1TELPART",
                                     "E1CODPOS",
                                     "E1CURP",
                                     "E1STSCTE",
                                     "E1USRSICAP",
                                     "E1FECALT",
                                     "E1HRAALT"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E1CTEGPO",
                                   "E1CLIENTE",
                                   "E1CUENTA",
                                   "E1APEPAT",
                                   "E1APEMAT",
                                   "E1NOMBRE",
                                   "E1NOMBRE2",
                                   "E1MESNAC",
                                   "E1DIANAC",
                                   "E1ANONAC",
                                   "E1CALLE",
                                   "E1COLONIA",
                                   "E1CODCIUD",
                                   "E1CODPAIS",
                                   "E1CODESTA",
                                   "E1CODCOL",
                                   "E1POBLAC",
                                   "E1ESTADO",
                                   "E1PAIS",
                                   "E1SEXO",
                                   "E1EDOCIV",
                                   "E1RFC",
                                   "E1TELPART",
                                   "E1CODPOS",
                                   "E1CURP",
                                   "E1STSCTE",
                                   "E1USRSICAP",
                                   "E1FECALT",
                                   "E1HRAALT"
                                 };
  final static String fid = "1090121160602";
  final static String rid = "358D2799D05E0";
  final static String fmtname = "CRF000201";
  final int FIELDCOUNT = 38;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private DecimalField fieldE1CTEGPO = null;
  private DecimalField fieldE1CLIENTE = null;
  private DecimalField fieldE1CUENTA = null;
  private CharacterField fieldE1APEPAT = null;
  private CharacterField fieldE1APEMAT = null;
  private CharacterField fieldE1NOMBRE = null;
  private CharacterField fieldE1NOMBRE2 = null;
  private DecimalField fieldE1MESNAC = null;
  private DecimalField fieldE1DIANAC = null;
  private DecimalField fieldE1ANONAC = null;
  private CharacterField fieldE1CALLE = null;
  private CharacterField fieldE1COLONIA = null;
  private DecimalField fieldE1CODCIUD = null;
  private CharacterField fieldE1CODPAIS = null;
  private DecimalField fieldE1CODESTA = null;
  private DecimalField fieldE1CODCOL = null;
  private CharacterField fieldE1POBLAC = null;
  private CharacterField fieldE1ESTADO = null;
  private CharacterField fieldE1PAIS = null;
  private CharacterField fieldE1SEXO = null;
  private CharacterField fieldE1EDOCIV = null;
  private CharacterField fieldE1RFC = null;
  private DecimalField fieldE1TELPART = null;
  private CharacterField fieldE1CODPOS = null;
  private CharacterField fieldE1CURP = null;
  private CharacterField fieldE1STSCTE = null;
  private CharacterField fieldE1USRSICAP = null;
  private DecimalField fieldE1FECALT = null;
  private DecimalField fieldE1HRAALT = null;

  /**
  * Constructor for CRF000201Message.
  */
  public CRF000201Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * this method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 450;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE1CTEGPO =
    new DecimalField(message, HEADERSIZE + 42, 13, 0, "E1CTEGPO");
    fields[10] = fieldE1CLIENTE =
    new DecimalField(message, HEADERSIZE + 55, 10, 0, "E1CLIENTE");
    fields[11] = fieldE1CUENTA =
    new DecimalField(message, HEADERSIZE + 65, 13, 0, "E1CUENTA");
    fields[12] = fieldE1APEPAT =
    new CharacterField(message, HEADERSIZE + 78, 30, "E1APEPAT");
    fields[13] = fieldE1APEMAT =
    new CharacterField(message, HEADERSIZE + 108, 30, "E1APEMAT");
    fields[14] = fieldE1NOMBRE =
    new CharacterField(message, HEADERSIZE + 138, 30, "E1NOMBRE");
    fields[15] = fieldE1NOMBRE2 =
    new CharacterField(message, HEADERSIZE + 168, 30, "E1NOMBRE2");
    fields[16] = fieldE1MESNAC =
    new DecimalField(message, HEADERSIZE + 198, 3, 0, "E1MESNAC");
    fields[17] = fieldE1DIANAC =
    new DecimalField(message, HEADERSIZE + 201, 3, 0, "E1DIANAC");
    fields[18] = fieldE1ANONAC =
    new DecimalField(message, HEADERSIZE + 204, 5, 0, "E1ANONAC");
    fields[19] = fieldE1CALLE =
    new CharacterField(message, HEADERSIZE + 209, 35, "E1CALLE");
    fields[20] = fieldE1COLONIA =
    new CharacterField(message, HEADERSIZE + 244, 35, "E1COLONIA");
    fields[21] = fieldE1CODCIUD =
    new DecimalField(message, HEADERSIZE + 279, 6, 0, "E1CODCIUD");
    fields[22] = fieldE1CODPAIS =
    new CharacterField(message, HEADERSIZE + 285, 3, "E1CODPAIS");
    fields[23] = fieldE1CODESTA =
    new DecimalField(message, HEADERSIZE + 288, 3, 0, "E1CODESTA");
    fields[24] = fieldE1CODCOL =
    new DecimalField(message, HEADERSIZE + 291, 6, 0, "E1CODCOL");
    fields[25] = fieldE1POBLAC =
    new CharacterField(message, HEADERSIZE + 297, 30, "E1POBLAC");
    fields[26] = fieldE1ESTADO =
    new CharacterField(message, HEADERSIZE + 327, 4, "E1ESTADO");
    fields[27] = fieldE1PAIS =
    new CharacterField(message, HEADERSIZE + 331, 20, "E1PAIS");
    fields[28] = fieldE1SEXO =
    new CharacterField(message, HEADERSIZE + 351, 1, "E1SEXO");
    fields[29] = fieldE1EDOCIV =
    new CharacterField(message, HEADERSIZE + 352, 1, "E1EDOCIV");
    fields[30] = fieldE1RFC =
    new CharacterField(message, HEADERSIZE + 353, 15, "E1RFC");
    fields[31] = fieldE1TELPART =
    new DecimalField(message, HEADERSIZE + 368, 12, 0, "E1TELPART");
    fields[32] = fieldE1CODPOS =
    new CharacterField(message, HEADERSIZE + 380, 15, "E1CODPOS");
    fields[33] = fieldE1CURP =
    new CharacterField(message, HEADERSIZE + 395, 18, "E1CURP");
    fields[34] = fieldE1STSCTE =
    new CharacterField(message, HEADERSIZE + 413, 1, "E1STSCTE");
    fields[35] = fieldE1USRSICAP =
    new CharacterField(message, HEADERSIZE + 414, 20, "E1USRSICAP");
    fields[36] = fieldE1FECALT =
    new DecimalField(message, HEADERSIZE + 434, 9, 0, "E1FECALT");
    fields[37] = fieldE1HRAALT =
    new DecimalField(message, HEADERSIZE + 443, 7, 0, "E1HRAALT");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E1CTEGPO using a String value.
  */
  public void setE1CTEGPO(String newvalue)
  {
    fieldE1CTEGPO.setString(newvalue);
  }

  /**
  * Get value of field E1CTEGPO as a String.
  */
  public String getE1CTEGPO()
  {
    return fieldE1CTEGPO.getString();
  }

  /**
  * Set numeric field E1CTEGPO using a BigDecimal value.
  */
  public void setE1CTEGPO(BigDecimal newvalue)
  {
    fieldE1CTEGPO.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1CTEGPO as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1CTEGPO()
  {
    return fieldE1CTEGPO.getBigDecimal();
  }

  /**
  * Set field E1CLIENTE using a String value.
  */
  public void setE1CLIENTE(String newvalue)
  {
    fieldE1CLIENTE.setString(newvalue);
  }

  /**
  * Get value of field E1CLIENTE as a String.
  */
  public String getE1CLIENTE()
  {
    return fieldE1CLIENTE.getString();
  }

  /**
  * Set numeric field E1CLIENTE using a BigDecimal value.
  */
  public void setE1CLIENTE(BigDecimal newvalue)
  {
    fieldE1CLIENTE.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1CLIENTE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1CLIENTE()
  {
    return fieldE1CLIENTE.getBigDecimal();
  }

  /**
  * Set field E1CUENTA using a String value.
  */
  public void setE1CUENTA(String newvalue)
  {
    fieldE1CUENTA.setString(newvalue);
  }

  /**
  * Get value of field E1CUENTA as a String.
  */
  public String getE1CUENTA()
  {
    return fieldE1CUENTA.getString();
  }

  /**
  * Set numeric field E1CUENTA using a BigDecimal value.
  */
  public void setE1CUENTA(BigDecimal newvalue)
  {
    fieldE1CUENTA.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1CUENTA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1CUENTA()
  {
    return fieldE1CUENTA.getBigDecimal();
  }

  /**
  * Set field E1APEPAT using a String value.
  */
  public void setE1APEPAT(String newvalue)
  {
    fieldE1APEPAT.setString(newvalue);
  }

  /**
  * Get value of field E1APEPAT as a String.
  */
  public String getE1APEPAT()
  {
    return fieldE1APEPAT.getString();
  }

  /**
  * Set field E1APEMAT using a String value.
  */
  public void setE1APEMAT(String newvalue)
  {
    fieldE1APEMAT.setString(newvalue);
  }

  /**
  * Get value of field E1APEMAT as a String.
  */
  public String getE1APEMAT()
  {
    return fieldE1APEMAT.getString();
  }

  /**
  * Set field E1NOMBRE using a String value.
  */
  public void setE1NOMBRE(String newvalue)
  {
    fieldE1NOMBRE.setString(newvalue);
  }

  /**
  * Get value of field E1NOMBRE as a String.
  */
  public String getE1NOMBRE()
  {
    return fieldE1NOMBRE.getString();
  }

  /**
  * Set field E1NOMBRE2 using a String value.
  */
  public void setE1NOMBRE2(String newvalue)
  {
    fieldE1NOMBRE2.setString(newvalue);
  }

  /**
  * Get value of field E1NOMBRE2 as a String.
  */
  public String getE1NOMBRE2()
  {
    return fieldE1NOMBRE2.getString();
  }

  /**
  * Set field E1MESNAC using a String value.
  */
  public void setE1MESNAC(String newvalue)
  {
    fieldE1MESNAC.setString(newvalue);
  }

  /**
  * Get value of field E1MESNAC as a String.
  */
  public String getE1MESNAC()
  {
    return fieldE1MESNAC.getString();
  }

  /**
  * Set numeric field E1MESNAC using a BigDecimal value.
  */
  public void setE1MESNAC(BigDecimal newvalue)
  {
    fieldE1MESNAC.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1MESNAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1MESNAC()
  {
    return fieldE1MESNAC.getBigDecimal();
  }

  /**
  * Set field E1DIANAC using a String value.
  */
  public void setE1DIANAC(String newvalue)
  {
    fieldE1DIANAC.setString(newvalue);
  }

  /**
  * Get value of field E1DIANAC as a String.
  */
  public String getE1DIANAC()
  {
    return fieldE1DIANAC.getString();
  }

  /**
  * Set numeric field E1DIANAC using a BigDecimal value.
  */
  public void setE1DIANAC(BigDecimal newvalue)
  {
    fieldE1DIANAC.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1DIANAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1DIANAC()
  {
    return fieldE1DIANAC.getBigDecimal();
  }

  /**
  * Set field E1ANONAC using a String value.
  */
  public void setE1ANONAC(String newvalue)
  {
    fieldE1ANONAC.setString(newvalue);
  }

  /**
  * Get value of field E1ANONAC as a String.
  */
  public String getE1ANONAC()
  {
    return fieldE1ANONAC.getString();
  }

  /**
  * Set numeric field E1ANONAC using a BigDecimal value.
  */
  public void setE1ANONAC(BigDecimal newvalue)
  {
    fieldE1ANONAC.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1ANONAC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1ANONAC()
  {
    return fieldE1ANONAC.getBigDecimal();
  }

  /**
  * Set field E1CALLE using a String value.
  */
  public void setE1CALLE(String newvalue)
  {
    fieldE1CALLE.setString(newvalue);
  }

  /**
  * Get value of field E1CALLE as a String.
  */
  public String getE1CALLE()
  {
    return fieldE1CALLE.getString();
  }

  /**
  * Set field E1COLONIA using a String value.
  */
  public void setE1COLONIA(String newvalue)
  {
    fieldE1COLONIA.setString(newvalue);
  }

  /**
  * Get value of field E1COLONIA as a String.
  */
  public String getE1COLONIA()
  {
    return fieldE1COLONIA.getString();
  }

  /**
  * Set field E1CODCIUD using a String value.
  */
  public void setE1CODCIUD(String newvalue)
  {
    fieldE1CODCIUD.setString(newvalue);
  }

  /**
  * Get value of field E1CODCIUD as a String.
  */
  public String getE1CODCIUD()
  {
    return fieldE1CODCIUD.getString();
  }

  /**
  * Set numeric field E1CODCIUD using a BigDecimal value.
  */
  public void setE1CODCIUD(BigDecimal newvalue)
  {
    fieldE1CODCIUD.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1CODCIUD as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1CODCIUD()
  {
    return fieldE1CODCIUD.getBigDecimal();
  }

  /**
  * Set field E1CODPAIS using a String value.
  */
  public void setE1CODPAIS(String newvalue)
  {
    fieldE1CODPAIS.setString(newvalue);
  }

  /**
  * Get value of field E1CODPAIS as a String.
  */
  public String getE1CODPAIS()
  {
    return fieldE1CODPAIS.getString();
  }

  /**
  * Set field E1CODESTA using a String value.
  */
  public void setE1CODESTA(String newvalue)
  {
    fieldE1CODESTA.setString(newvalue);
  }

  /**
  * Get value of field E1CODESTA as a String.
  */
  public String getE1CODESTA()
  {
    return fieldE1CODESTA.getString();
  }

  /**
  * Set numeric field E1CODESTA using a BigDecimal value.
  */
  public void setE1CODESTA(BigDecimal newvalue)
  {
    fieldE1CODESTA.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1CODESTA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1CODESTA()
  {
    return fieldE1CODESTA.getBigDecimal();
  }

  /**
  * Set field E1CODCOL using a String value.
  */
  public void setE1CODCOL(String newvalue)
  {
    fieldE1CODCOL.setString(newvalue);
  }

  /**
  * Get value of field E1CODCOL as a String.
  */
  public String getE1CODCOL()
  {
    return fieldE1CODCOL.getString();
  }

  /**
  * Set numeric field E1CODCOL using a BigDecimal value.
  */
  public void setE1CODCOL(BigDecimal newvalue)
  {
    fieldE1CODCOL.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1CODCOL as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1CODCOL()
  {
    return fieldE1CODCOL.getBigDecimal();
  }

  /**
  * Set field E1POBLAC using a String value.
  */
  public void setE1POBLAC(String newvalue)
  {
    fieldE1POBLAC.setString(newvalue);
  }

  /**
  * Get value of field E1POBLAC as a String.
  */
  public String getE1POBLAC()
  {
    return fieldE1POBLAC.getString();
  }

  /**
  * Set field E1ESTADO using a String value.
  */
  public void setE1ESTADO(String newvalue)
  {
    fieldE1ESTADO.setString(newvalue);
  }

  /**
  * Get value of field E1ESTADO as a String.
  */
  public String getE1ESTADO()
  {
    return fieldE1ESTADO.getString();
  }

  /**
  * Set field E1PAIS using a String value.
  */
  public void setE1PAIS(String newvalue)
  {
    fieldE1PAIS.setString(newvalue);
  }

  /**
  * Get value of field E1PAIS as a String.
  */
  public String getE1PAIS()
  {
    return fieldE1PAIS.getString();
  }

  /**
  * Set field E1SEXO using a String value.
  */
  public void setE1SEXO(String newvalue)
  {
    fieldE1SEXO.setString(newvalue);
  }

  /**
  * Get value of field E1SEXO as a String.
  */
  public String getE1SEXO()
  {
    return fieldE1SEXO.getString();
  }

  /**
  * Set field E1EDOCIV using a String value.
  */
  public void setE1EDOCIV(String newvalue)
  {
    fieldE1EDOCIV.setString(newvalue);
  }

  /**
  * Get value of field E1EDOCIV as a String.
  */
  public String getE1EDOCIV()
  {
    return fieldE1EDOCIV.getString();
  }

  /**
  * Set field E1RFC using a String value.
  */
  public void setE1RFC(String newvalue)
  {
    fieldE1RFC.setString(newvalue);
  }

  /**
  * Get value of field E1RFC as a String.
  */
  public String getE1RFC()
  {
    return fieldE1RFC.getString();
  }

  /**
  * Set field E1TELPART using a String value.
  */
  public void setE1TELPART(String newvalue)
  {
    fieldE1TELPART.setString(newvalue);
  }

  /**
  * Get value of field E1TELPART as a String.
  */
  public String getE1TELPART()
  {
    return fieldE1TELPART.getString();
  }

  /**
  * Set numeric field E1TELPART using a BigDecimal value.
  */
  public void setE1TELPART(BigDecimal newvalue)
  {
    fieldE1TELPART.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1TELPART as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1TELPART()
  {
    return fieldE1TELPART.getBigDecimal();
  }

  /**
  * Set field E1CODPOS using a String value.
  */
  public void setE1CODPOS(String newvalue)
  {
    fieldE1CODPOS.setString(newvalue);
  }

  /**
  * Get value of field E1CODPOS as a String.
  */
  public String getE1CODPOS()
  {
    return fieldE1CODPOS.getString();
  }

  /**
  * Set field E1CURP using a String value.
  */
  public void setE1CURP(String newvalue)
  {
    fieldE1CURP.setString(newvalue);
  }

  /**
  * Get value of field E1CURP as a String.
  */
  public String getE1CURP()
  {
    return fieldE1CURP.getString();
  }

  /**
  * Set field E1STSCTE using a String value.
  */
  public void setE1STSCTE(String newvalue)
  {
    fieldE1STSCTE.setString(newvalue);
  }

  /**
  * Get value of field E1STSCTE as a String.
  */
  public String getE1STSCTE()
  {
    return fieldE1STSCTE.getString();
  }

  /**
  * Set field E1USRSICAP using a String value.
  */
  public void setE1USRSICAP(String newvalue)
  {
    fieldE1USRSICAP.setString(newvalue);
  }

  /**
  * Get value of field E1USRSICAP as a String.
  */
  public String getE1USRSICAP()
  {
    return fieldE1USRSICAP.getString();
  }

  /**
  * Set field E1FECALT using a String value.
  */
  public void setE1FECALT(String newvalue)
  {
    fieldE1FECALT.setString(newvalue);
  }

  /**
  * Get value of field E1FECALT as a String.
  */
  public String getE1FECALT()
  {
    return fieldE1FECALT.getString();
  }

  /**
  * Set numeric field E1FECALT using a BigDecimal value.
  */
  public void setE1FECALT(BigDecimal newvalue)
  {
    fieldE1FECALT.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1FECALT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1FECALT()
  {
    return fieldE1FECALT.getBigDecimal();
  }

  /**
  * Set field E1HRAALT using a String value.
  */
  public void setE1HRAALT(String newvalue)
  {
    fieldE1HRAALT.setString(newvalue);
  }

  /**
  * Get value of field E1HRAALT as a String.
  */
  public String getE1HRAALT()
  {
    return fieldE1HRAALT.getString();
  }

  /**
  * Set numeric field E1HRAALT using a BigDecimal value.
  */
  public void setE1HRAALT(BigDecimal newvalue)
  {
    fieldE1HRAALT.setBigDecimal(newvalue);
  }

  /**
  * return value of numeric field E1HRAALT as a BigDecimal.
  */
  public BigDecimal getBigDecimalE1HRAALT()
  {
    return fieldE1HRAALT.getBigDecimal();
  }

}