package com.sicap.clientes.helpers;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Table;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.sicap.clientes.dao.CatalogoDAO;
import com.sicap.clientes.dao.SucursalDAO;
import com.sicap.clientes.exceptions.ClientesException;
import com.sicap.clientes.util.ClientesConstants;
import com.sicap.clientes.util.ClientesUtil;
import com.sicap.clientes.util.ConvertNumberToString;
import com.sicap.clientes.util.Convertidor;
import com.sicap.clientes.util.FechasUtil;
import com.sicap.clientes.util.FormatUtil;
import com.sicap.clientes.vo.CicloGrupalVO;
import com.sicap.clientes.vo.ClienteVO;
import com.sicap.clientes.vo.ConsultaEfectuadaVO;
import com.sicap.clientes.vo.CuentaVO;
import com.sicap.clientes.vo.DomicilioVO;
import com.sicap.clientes.vo.GrupoVO;
import com.sicap.clientes.vo.ParametroVO;
import com.sicap.clientes.vo.ReporteCirculoEmpleoVO;
import com.sicap.clientes.vo.ReporteCirculoVO;
import com.sicap.clientes.vo.ResumenVO;
import com.sicap.clientes.vo.ScoreFicoVO;
import com.sicap.clientes.vo.SolicitudVO;
import com.sicap.clientes.vo.SucursalVO;
import com.sicap.clientes.vo.TasaInteresVO;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.TreeMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.log4j.Logger;

public class ReporteCreditoPDFHelper {

    Document document;
    Font titleFont;
    Font headFont;
    Font tableFont;
    Font labelFont;
    Font smallFont;
    Font numberFont;
    int letra;
    Table dataTable;
    String fechaHoy;
    OutputStream out = new ByteArrayOutputStream();
    private static Logger myLogger = Logger.getLogger(ReporteCreditoPDFHelper.class);

    public OutputStream doReporteCredito(ReporteCirculoVO respuesta) {

        document = new Document(PageSize.LETTER);
        try {
            PdfWriter.getInstance(document, out);
            letra = Font.getFamilyIndex("Arial");
            titleFont = new Font(letra, 8F, 1);
            headFont = new Font(letra, 10F, 1);
            tableFont = new Font(letra, 5.0F, 1);
            labelFont = new Font(letra, 5.0F, 2);
            smallFont = new Font(letra, 4.0F, 1);
            numberFont = new Font(letra, 5.0F, 1);
            document.setMargins(40, 40, 40, 40);
            document.open();
            contenidoReporte(respuesta);
            document.close();
        } catch (Exception exception) {
            myLogger.error("doReporteCredito", exception);
        }
        return out;
    }

    private void contenidoReporte(ReporteCirculoVO respuesta) {

        try {
            Paragraph p = null;
            Chunk ck = null;
            String texto = "";
            PdfPTable tabla = null;
            PdfPCell cell = null;
            int cont = 0;
            Iterator iterator = null;
            CatalogoDAO paramDao = new CatalogoDAO();
            ParametroVO paramVO = new ParametroVO();
            paramVO = paramDao.getParametro("RUTA_IMAGEN_CIRCULO");
            Image logo = Image.getInstance(paramVO.valor);
            logo.scaleToFit(60, 60);
            logo.setAlignment(Chunk.ALIGN_LEFT);
            document.add(logo);
            p = new Paragraph();
            texto = "_______________________________________________________________________________________________________________________";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.NORMAL, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_CENTER);
            p.setLeading(12);
            document.add(p);
            p = new Paragraph();
            texto = "Reporte de Crédito para Finanzas Populares y Microfinanzas";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 10, Font.NORMAL, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_RIGHT);
            document.add(p);
            p = new Paragraph();
            texto = "_______________________________________________________________________________________________________________________";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.NORMAL, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_CENTER);
            p.setLeading(12);
            document.add(p);
            /*DATOS GENERALES*/
            p = new Paragraph();
            texto = "Datos Generales\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            int col[] = {20, 30, 20, 30};
            tabla = new PdfPTable(4);
            tabla.setWidthPercentage(100);
            tabla.setWidths(col);
            texto = "Nombre(s):  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 1);
            tabla.addCell(cell);
            texto = respuesta.getPersonas().getNombre();
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 2);
            tabla.addCell(cell);
            texto = "Numero de Consulta:  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 2);
            tabla.addCell(cell);
            texto = respuesta.getEncabezadoCirculo().getFolioConsulta();
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 3);
            tabla.addCell(cell);
            texto = "Paterno / Materno:  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 4);
            tabla.addCell(cell);
            texto = respuesta.getPersonas().getPaterno() + " " + respuesta.getPersonas().getMaterno();
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 5);
            tabla.addCell(cell);
            texto = "Fecha de consulta:  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 5);
            tabla.addCell(cell);
            texto = Convertidor.dateToString(new Date());
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 6);
            tabla.addCell(cell);
            texto = "Fecha Nacimiento:  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 4);
            tabla.addCell(cell);
            java.util.Date fNacimiento = respuesta.getPersonas().getNacimiento();
            if (fNacimiento != null) {
                texto = Convertidor.dateToString(respuesta.getPersonas().getNacimiento());
            }
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 5);
            tabla.addCell(cell);
            texto = "";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cell.setColspan(2);
            bordeCelda(cell, 6);
            tabla.addCell(cell);
            texto = "RFC:  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 4);
            tabla.addCell(cell);
            texto = respuesta.getPersonas().getRfc();
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 5);
            tabla.addCell(cell);
            texto = "";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cell.setColspan(2);
            bordeCelda(cell, 6);
            tabla.addCell(cell);
            texto = "CURP:  ";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            bordeCelda(cell, 7);
            tabla.addCell(cell);
            texto = respuesta.getPersonas().getCurp();
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.BOLD));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
            bordeCelda(cell, 8);
            tabla.addCell(cell);
            texto = "";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cell.setColspan(2);
            bordeCelda(cell, 9);
            tabla.addCell(cell);
            document.add(tabla);
            /*DOMICILIOS*/
            p = new Paragraph();
            texto = "Domicilios\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            int col2[] = {3, 20, 15, 15, 15, 7, 5, 10, 10};
            tabla = new PdfPTable(9);
            tabla.setWidthPercentage(100);
            tabla.setWidths(col2);
            texto = "#";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Calle y Número";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Colonia";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Del/Mpio";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Ciudad";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Estado";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "CP";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Teléfono";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Fecha de Registro";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            DomicilioVO domicilio = null;
            iterator = respuesta.getDomicilios().iterator();
            cont = 0;
            while (iterator.hasNext()) {
                cont++;
                domicilio = (DomicilioVO) iterator.next();
                texto = cont + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getCalle();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getColonia();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getDelegacion();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getCiudad();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getEstado();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getCp();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = domicilio.getTelefono();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(domicilio.getRegistro());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
            }
            document.add(tabla);
            /*Empleos*/
            p = new Paragraph();
            texto = "Empleos\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            int col3[] = {3, 10, 10, 5, 10, 10, 10, 10, 10, 7, 7, 8};
            tabla = new PdfPTable(12);
            tabla.setWidthPercentage(100);
            tabla.setWidths(col3);
            texto = "#";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Compañia";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Puesto";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Salario";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Calle y Número";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Colonia";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Municipio";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Ciudad";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Estado";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "CP";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Teléfono";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Fecha de Registro";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            ReporteCirculoEmpleoVO empleo = null;
            iterator = respuesta.getEmpleos().iterator();
            cont = 0;
            while (iterator.hasNext()) {
                cont++;
                empleo = (ReporteCirculoEmpleoVO) iterator.next();
                texto = cont + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getEmpresa();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getPuesto();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getSueldo() + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getCalle();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getColonia();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getMunicipio();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getCiudad();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getEstado();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getCp();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = empleo.getTelefono();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(empleo.getFechaRegistro());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
            }
            if (empleo == null) {
                texto = "Sin Registros";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.ITALIC));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell.setColspan(12);
                tabla.addCell(cell);
            }
            document.add(tabla);
            /*RESUMEN PRODUCTO*/
            p = new Paragraph();
            texto = "Resumen por Producto\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            //int col3[] = {3, 10, 10, 5, 10, 10, 10, 10, 10, 7, 7, 8};
            tabla = new PdfPTable(9);
            tabla.setWidthPercentage(100);
            //tabla.setWidths(col3);
            texto = "Descripción";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(2);
            tabla.addCell(cell);
            texto = "Montos (Pesos)";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(4);
            tabla.addCell(cell);
            texto = "Montos Requeridos por Corte (Pesos)";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(3);
            tabla.addCell(cell);
            texto = "Producto";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Cuentas";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Limite";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Aprobado";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Actual";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Vencido";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Pago Semanal";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Pago Quincenal";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Pago Mensual";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            ResumenProductoHelper resumenProducto = new ResumenProductoHelper(respuesta.getCuentas());
            ResumenVO resumen = null;
            List list = resumenProducto.doResumen();
            iterator = list.iterator();
            while (iterator.hasNext()) {
                resumen = (ResumenVO) iterator.next();
                texto = resumen.getDescripcion();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
                cell = new PdfPCell(p);
                if (texto.equals("TOTALES")) {
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                } else {
                    cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                }
                tabla.addCell(cell);
                texto = resumen.getTotalCuentas() + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getLimite());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getAprobado());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getActual());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getVencido());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getPagoSemanal());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getPagoQuincenal());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(resumen.getPagoMensual());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
            }
            if (resumen == null) {
                texto = "Sin Registros";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.ITALIC));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell.setColspan(12);
                tabla.addCell(cell);
            }
            document.add(tabla);
            /*CUENTAS*/
            p = new Paragraph();
            texto = "Detalle de las Cuentas\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            //int col3[] = {3, 10, 10, 5, 10, 10, 10, 10, 10, 7, 7, 8};
            tabla = new PdfPTable(18);
            tabla.setWidthPercentage(100);
            //tabla.setWidths(col3);
            texto = "Descripción";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 7, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(5);
            tabla.addCell(cell);
            texto = "Montos";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 7, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(5);
            tabla.addCell(cell);
            texto = "Fechas";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 7, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(4);
            tabla.addCell(cell);
            texto = "Forma de Pago";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 7, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Peor Atraso";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 7, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(3);
            tabla.addCell(cell);
            texto = "";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(5);
            tabla.addCell(cell);
            texto = "(Pesos)";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(5);
            tabla.addCell(cell);
            texto = "(dd/mm/aa)";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(4);
            tabla.addCell(cell);
            texto = "(Periodos)";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Atrasos";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Monto";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Fecha";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Producto";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Crédito";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Otorgante";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Plazo";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Limite";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Aprobado";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Actual";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Vencido";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "a Pagar";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Reporte";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Apertura";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Cierre";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Pago";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Últimos 12";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Situación";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(3);
            tabla.addCell(cell);
            CuentaVO cuenta = null;
            iterator = respuesta.getCuentas().iterator();
            while (iterator.hasNext()) {
                cuenta = (CuentaVO) iterator.next();
                texto = cuenta.getFrecuencia();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = cuenta.getDescTipoCredito();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = cuenta.getTipoCuenta();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = cuenta.getOtorgante();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = cuenta.getNumeroPagos() + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(cuenta.getLimiteCredito());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(cuenta.getCreditoMaximo());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(cuenta.getSaldoActual());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(cuenta.getSaldoVencido());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(cuenta.getAPagar());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(cuenta.getFechaActualizacion());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(cuenta.getFechaApertura());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(cuenta.getFechaCierre());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(cuenta.getFechaUltimoPago());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = cuenta.getHistorial();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = cuenta.getPeorAtraso() + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = FormatUtil.formatDobleMiles(cuenta.getSaldoVencido());
                if (cuenta.getCvePrevencion().equals("UP")||cuenta.getCvePrevencion().equals("FD")){
                    texto += "\n"+cuenta.getCvePrevencion();
                }
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = Convertidor.dateToStringCDC(cuenta.getFechaPeorAtraso());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 4, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
            }
            if (cuenta == null) {
                texto = "Sin Registros";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.ITALIC));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell.setColspan(12);
                tabla.addCell(cell);
            }
            document.add(tabla);
            /*SCORE*/
            p = new Paragraph();
            texto = "Score FICO\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            int col4[] = {20, 60};
            tabla = new PdfPTable(2);
            tabla.setWidthPercentage(60);
            tabla.setWidths(col4);
            ScoreFicoVO score = null;
            ScoreCirculoHelp scoreHelp = new ScoreCirculoHelp();
            iterator = respuesta.getScoreFico().iterator();
            while (iterator.hasNext()) {
                score = (ScoreFicoVO) iterator.next();
                texto = "Descripción:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = score.getNombre();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = "Codigo:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = score.getCodigo() + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = "Score:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = score.getValor() + "";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = "Razon 1:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                System.out.println("score.getRazon1() " + score.getRazon1());
                texto = scoreHelp.getRazonScore(score.getRazon1());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = "Razon 2:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = scoreHelp.getRazonScore(score.getRazon2());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = "Razon 3:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = scoreHelp.getRazonScore(score.getRazon3());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = "Razon 4:  ";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = scoreHelp.getRazonScore(score.getRazon4());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
            }
            if (score == null) {
                texto = "Sin Registros";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.ITALIC));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell.setColspan(12);
                tabla.addCell(cell);
            }
            document.add(tabla);
            /*CONSULTAS*/
            p = new Paragraph();
            texto = "Consultas Realizadas\n\n";
            ck = new Chunk(texto, new Font(Font.HELVETICA, 8, Font.BOLD, Color.BLACK));
            p.add(ck);
            p.setAlignment(Chunk.ALIGN_LEFT);
            document.add(p);
            //int col4[] = {20, 60};
            tabla = new PdfPTable(5);
            tabla.setWidthPercentage(100);
            //tabla.setWidths(col4);
            texto = "Fecha de Consulta";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Otorgante";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Tipo de Crédito";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Monto";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            texto = "Moneda";
            p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
            cell = new PdfPCell(p);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(cell);
            ConsultaEfectuadaVO consulta = null;
            iterator = respuesta.getConsultas().iterator();
            while (iterator.hasNext()) {
                consulta = (ConsultaEfectuadaVO) iterator.next();
                texto = Convertidor.dateToStringCDC(consulta.getFechaConsulta());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                tabla.addCell(cell);
                texto = consulta.getOtorgante();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = consulta.getTipoCredito();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
                texto = FormatUtil.formatDoble(consulta.getMonto());
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tabla.addCell(cell);
                texto = consulta.getMoneda();
                p = new Paragraph(texto, new Font(Font.HELVETICA, 8, Font.NORMAL));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                tabla.addCell(cell);
            }
            if (consulta == null) {
                texto = "Sin Registros";
                p = new Paragraph(texto, new Font(Font.HELVETICA, 6, Font.ITALIC));
                cell = new PdfPCell(p);
                cell.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell.setColspan(12);
                tabla.addCell(cell);
            }
            document.add(tabla);

        } catch (Exception e) {
            myLogger.error("contenidoReporte", e);
        }
    }

    private PdfPCell bordeCelda(PdfPCell celda, int tipo) {

        if (tipo == 1) {
            celda.setBorderWidthRight(0f);
            celda.setBorderWidthBottom(0f);
        } else if (tipo == 2) {
            celda.setBorderWidthLeft(0f);
            celda.setBorderWidthRight(0f);
            celda.setBorderWidthBottom(0f);
        } else if (tipo == 3) {
            celda.setBorderWidthLeft(0f);
            celda.setBorderWidthBottom(0f);
        } else if (tipo == 4) {
            celda.setBorderWidthRight(0f);
            celda.setBorderWidthTop(0f);
            celda.setBorderWidthBottom(0f);
        } else if (tipo == 5) {
            celda.setBorderWidthLeft(0f);
            celda.setBorderWidthRight(0f);
            celda.setBorderWidthTop(0f);
            celda.setBorderWidthBottom(0f);
        } else if (tipo == 6) {
            celda.setBorderWidthLeft(0f);
            celda.setBorderWidthTop(0f);
            celda.setBorderWidthBottom(0f);
        } else if (tipo == 7) {
            celda.setBorderWidthRight(0f);
            celda.setBorderWidthTop(0f);
        } else if (tipo == 8) {
            celda.setBorderWidthLeft(0f);
            celda.setBorderWidthRight(0f);
            celda.setBorderWidthTop(0f);
        } else if (tipo == 9) {
            celda.setBorderWidthLeft(0f);
            celda.setBorderWidthTop(0f);
        }
        return celda;
    }

}
