package com.sicap.clientes.vo;

import java.io.Serializable;
import java.sql.Date;

public class SaldoT24VO implements Serializable{
	
	public int numCliente;
	public Date fechaInf;
	public Date fechaGeneracion;
	public String nombre;
	public String direccion1;
	public String direccion2;
	public String telefono;
	public int numSucursal;
	public String nombreSucursal;
	public int ciclo;
	public String rfc;
	public int numCuotas;
	public int numCuotasRestantes;
	public int destinoCredito;
	public Date fechaDisposicion;
	public Date fechaVencimiento;
	public double responsabilidadTotal;
	public double montoLineaCredito;
	public double saldoInsoluto;
	public double comision;
	public double ivaComision;
	public double desembolso;
	public int formaAmortizacion;
	public double montoAmortizacion;
	public String frecuenciaAmortizacion;
	public int formaPagoIntereses;
	public double montoInteresesPorCobrar;
	public int moneda;
	public double tasaBruta;
	public double tasaReferencia;
	public double interesesDevNoCobrados;
	public double capitalVencido;
	public double interesesVencidos;
	public double interesMoratorio;
	public double feeVencidos;
	public int situacionActualCredito;
	public Date fechaIncumplimiento;
	public Date fechaEntradaCartVencida;
	public int diasVencidos;
	public int diasTranscurridos;
	public int numeroPagosVencidos;
	public double multa;
	public double ivaMulta;
	public double ivaMoratorio;
	public double totalVencido;
	public double totalExigible;
	public double totalMulta;
	public double totalMoratorios;
	public double capitalPagado;
	public double interesPagado;
	public double totalPagado;
	public String ejecutivo;
	public int diasTotales;
	public double interesFuturo;
	public double moratorioPagado;
	public double montoLiquidacionAnticipada;
	public Date fechaProximoVencimiento;
	public double interesAlDia;
	public Date fechaSigAmortizacion;
	public int fuenteFondeo;
	public int numOperacion;
	public int tipoGtiaReal;
	public int tipoRelacion;
	public int tipoIndustria;
	public double montoAprobado;
	public String noCuenta;
	public String nombreProducto;
	
	public SaldoT24VO(){
		
		  numCliente = 0;
		  fechaInf = null;
		  fechaGeneracion = null;
		  nombre = null;
		  direccion1 = null;
		  direccion2 = null;
		  telefono = null;
		  numSucursal = 0;
		  nombreSucursal = null;
		  ciclo = 0;
		  rfc = null;
		  numCuotas = 0;
		  numCuotasRestantes = 0;
		  destinoCredito = 0;
		  fechaDisposicion = null;
		  fechaVencimiento = null;
		  responsabilidadTotal = 0;
		  montoLineaCredito = 0;
		  saldoInsoluto = 0;
		  comision = 0;
		  ivaComision = 0;
		  desembolso = 0;
		  formaAmortizacion = 0;
		  montoAmortizacion = 0;
		  frecuenciaAmortizacion = null;
		  formaPagoIntereses = 0;
		  montoInteresesPorCobrar = 0;
		  moneda = 0;
		  tasaBruta = 0;
		  tasaReferencia = 0;
		  interesesDevNoCobrados = 0;
		  capitalVencido = 0;
		  interesesVencidos = 0;
		  interesMoratorio = 0;
		  feeVencidos = 0;
		  situacionActualCredito = 0;
		  fechaIncumplimiento = null;
		  fechaEntradaCartVencida = null;
		  diasVencidos = 0;
		  diasTranscurridos = 0;
		  numeroPagosVencidos = 0;
		  multa = 0;
		  ivaMulta = 0;
		  ivaMoratorio = 0;
		  totalVencido = 0;
		  totalExigible = 0;
		  totalMulta = 0;
		  totalMoratorios = 0;
		  capitalPagado = 0;
		  interesPagado = 0;
		  totalPagado = 0;
		  ejecutivo = null;
		  diasTotales = 0;
		  interesFuturo = 0;
		  moratorioPagado = 0;
		  montoLiquidacionAnticipada = 0;
		  fechaProximoVencimiento = null;
		  interesAlDia = 0;
		  fechaSigAmortizacion = null;
		  fuenteFondeo = 0;
		  numOperacion = 0;
		  tipoGtiaReal = 0;
		  tipoRelacion = 0;
		  tipoIndustria = 0;
		  montoAprobado = 0;
		  noCuenta = null;
		  nombreProducto = null;
	}
	
	public String toString(){
		
		String respuesta = null;
		respuesta = "numCliente=[" + numCliente + "],";
		respuesta += "fechaInf=[" + fechaInf + "],";
		respuesta += "fechaGeneracion=[" + fechaGeneracion + "],";
		respuesta += "nombre=[" + nombre + "],";
		respuesta += "direccion1=[" + direccion1 + "],";
		respuesta += "direccion2=[" + direccion2 + "],";
		respuesta += "telefono=[" + telefono + "],";
		respuesta += "numSucursal=[" + numSucursal + "],";
		respuesta += "nombreSucursal=[" + nombreSucursal + "],";
		respuesta += "ciclo=[" + ciclo + "],";
		respuesta += "rfc=[" + rfc + "],";
		respuesta += "numCuotas=[" + numCuotas + "],";
		respuesta += "numCuotasRestantes=[" + numCuotasRestantes + "],";
		respuesta += "destinoCredito=[" + destinoCredito + "],";
		respuesta += "fechaDisposicion=[" + fechaDisposicion + "],";
		respuesta += "fechaVencimiento=[" + fechaVencimiento + "],";
		respuesta += "responsabilidadTotal=[" + responsabilidadTotal + "],";
		respuesta += "montoLineaCredito=[" + montoLineaCredito + "],";
		respuesta += "saldoInsoluto=[" + saldoInsoluto + "],";
		respuesta += "comision=[" + comision + "],";
		respuesta += "ivaComision=[" + ivaComision + "],";
		respuesta += "desembolso=[" + desembolso + "],";
		respuesta += "formaAmortizacion=[" + formaAmortizacion + "],";
		respuesta += "montoAmortizacion=[" + montoAmortizacion + "],";
		respuesta += "frecuenciaAmortizacion=[" + frecuenciaAmortizacion + "],";
		respuesta += "formaPagoIntereses=[" + formaPagoIntereses + "],";
		respuesta += "montoInteresesPorCobrar=[" + montoInteresesPorCobrar + "],";
		respuesta += "moneda=[" + moneda + "],";
		respuesta += "tasaBruta=[" + tasaBruta + "],";
		respuesta += "tasaReferencia=[" + tasaReferencia + "],";
		respuesta += "interesesDevNoCobrados=[" + interesesDevNoCobrados + "],";
		respuesta += "capitalVencido=[" + capitalVencido + "],";
		respuesta += "interesesVencidos=[" + interesesVencidos + "],";
		respuesta += "interesMoratorio=[" + interesMoratorio + "],";
		respuesta += "feeVencidos=[" + feeVencidos + "],";
		respuesta += "situacionActualCredito=[" + situacionActualCredito + "],";
		respuesta += "fechaIncumplimiento=[" + fechaIncumplimiento + "],";
		respuesta += "fechaEntradaCartVencida=[" + fechaEntradaCartVencida + "],";
		respuesta += "diasVencidos=[" + diasVencidos + "],";
		respuesta += "diasTranscurridos=[" + diasTranscurridos + "],";
		respuesta += "numeroPagosVencidos=[" + numeroPagosVencidos + "],";
		respuesta += "multa=[" + multa + "],";
		respuesta += "ivaMulta=[" + ivaMulta + "],";
		respuesta += "ivaMoratorio=[" + ivaMoratorio + "],";
		respuesta += "totalVencido=[" + totalVencido + "],";
		respuesta += "totalExigible=[" + totalExigible + "],";
		respuesta += "totalMulta=[" + totalMulta + "],";
		respuesta += "totalMoratorios=[" + totalMoratorios + "],";
		respuesta += "capitalPagado=[" + capitalPagado + "],";
		respuesta += "interesPagado=[" + interesPagado + "],";
		respuesta += "totalPagado=[" + totalPagado + "],";
		respuesta += "ejecutivo=[" + ejecutivo + "],";
		respuesta += "diasTotales=[" + diasTotales + "],";
		respuesta += "interesFuturo=[" + interesFuturo + "],";
		respuesta += "moratorioPagado=[" + moratorioPagado + "],";
		respuesta += "montoLiquidacionAnticipada=[" + montoLiquidacionAnticipada + "],";
		respuesta += "fechaProximoVencimiento=[" + fechaProximoVencimiento + "],";
		respuesta += "interesAlDia=[" + interesAlDia + "],";
		respuesta += "fechaSigAmortizacion=[" + fechaSigAmortizacion + "],";
		respuesta += "fuenteFondeo=[" + fuenteFondeo + "],";
		respuesta += "numOperacion=[" + numOperacion + "],";
		respuesta += "tipoGtiaReal=[" + tipoGtiaReal + "],";
		respuesta += "tipoRelacion=[" + tipoRelacion + "],";
		respuesta += "tipoIndustria=[" + tipoIndustria + "],";
		respuesta += "montoAprobado=[" + montoAprobado + "],";
		respuesta += "noCuenta=[" + noCuenta + "],";
		respuesta += "nombreProducto=[" + nombreProducto + "]";
		
		return respuesta;
	}
}
