package datapro.eibs.beans;

import java.math.BigDecimal;
import java.util.Hashtable;

import datapro.eibs.sockets.CharacterField;
import datapro.eibs.sockets.DecimalField;
import datapro.eibs.sockets.MessageField;
import datapro.eibs.sockets.MessageRecord;

/**
* Class generated by AS/400 CRTCLASS command from CRF000401 physical file definition.
* 
* File level identifier is 1090416100036.
* Record format level identifier is 4931B5D253EC6.
*/

public class CRF000401Message extends MessageRecord
{
  final static String fldnames[] = {
                                     "H01USERID",
                                     "H01PROGRM",
                                     "H01TIMSYS",
                                     "H01SCRCOD",
                                     "H01OPECOD",
                                     "H01FLGMAS",
                                     "H01FLGWK1",
                                     "H01FLGWK2",
                                     "H01FLGWK3",
                                     "E01CSI",
                                     "E01CUN",
                                     "E01REF",
                                     "E01ACC",
                                     "E01AC1",
                                     "E01BRN",
                                     "E01FAU",
                                     "E01FDE",
                                     "E01FA1",
                                     "E01FA2",
                                     "E01FVE",
                                     "E01VCU",
                                     "E01NCU",
                                     "E01FPA",
                                     "E01OAM",
                                     "E01MDE",
                                     "E01MSE",
                                     "E01MCS",
                                     "E01MIC",
                                     "E01RTE",
                                     "E01TIN",
                                     "E01TIM",
                                     "E01TCO",
                                     "E01TIV",
                                     "E01CDE",
                                     "E01FON",
                                     "E01BDE",
                                     "E01ORD",
                                     "E01NDE",
                                     "E01REE",
                                     "E01USI",
                                     "E01FSI",
                                     "E01HSI",
                                     "E01FI1",
                                     "E01FI2",
                                     "E01FI3",
                                     "E01FI4"
                                   };
  final static String tnames[] = {
                                   "H01USERID",
                                   "H01PROGRM",
                                   "H01TIMSYS",
                                   "H01SCRCOD",
                                   "H01OPECOD",
                                   "H01FLGMAS",
                                   "H01FLGWK1",
                                   "H01FLGWK2",
                                   "H01FLGWK3",
                                   "E01CSI",
                                   "E01CUN",
                                   "E01REF",
                                   "E01ACC",
                                   "E01AC1",
                                   "E01BRN",
                                   "E01FAU",
                                   "E01FDE",
                                   "E01FA1",
                                   "E01FA2",
                                   "E01FVE",
                                   "E01VCU",
                                   "E01NCU",
                                   "E01FPA",
                                   "E01OAM",
                                   "E01MDE",
                                   "E01MSE",
                                   "E01MCS",
                                   "E01MIC",
                                   "E01RTE",
                                   "E01TIN",
                                   "E01TIM",
                                   "E01TCO",
                                   "E01TIV",
                                   "E01CDE",
                                   "E01FON",
                                   "E01BDE",
                                   "E01ORD",
                                   "E01NDE",
                                   "E01REE",
                                   "E01USI",
                                   "E01FSI",
                                   "E01HSI",
                                   "E01FI1",
                                   "E01FI2",
                                   "E01FI3",
                                   "E01FI4"
                                 };
  final static String fid = "1090416100036";
  final static String rid = "4931B5D253EC6";
  final static String fmtname = "CRF000401";
  final int FIELDCOUNT = 46;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldH01USERID = null;
  private CharacterField fieldH01PROGRM = null;
  private CharacterField fieldH01TIMSYS = null;
  private CharacterField fieldH01SCRCOD = null;
  private CharacterField fieldH01OPECOD = null;
  private CharacterField fieldH01FLGMAS = null;
  private CharacterField fieldH01FLGWK1 = null;
  private CharacterField fieldH01FLGWK2 = null;
  private CharacterField fieldH01FLGWK3 = null;
  private DecimalField fieldE01CSI = null;
  private DecimalField fieldE01CUN = null;
  private CharacterField fieldE01REF = null;
  private DecimalField fieldE01ACC = null;
  private DecimalField fieldE01AC1 = null;
  private DecimalField fieldE01BRN = null;
  private DecimalField fieldE01FAU = null;
  private DecimalField fieldE01FDE = null;
  private DecimalField fieldE01FA1 = null;
  private DecimalField fieldE01FA2 = null;
  private DecimalField fieldE01FVE = null;
  private DecimalField fieldE01VCU = null;
  private DecimalField fieldE01NCU = null;
  private DecimalField fieldE01FPA = null;
  private DecimalField fieldE01OAM = null;
  private DecimalField fieldE01MDE = null;
  private DecimalField fieldE01MSE = null;
  private DecimalField fieldE01MCS = null;
  private DecimalField fieldE01MIC = null;
  private DecimalField fieldE01RTE = null;
  private DecimalField fieldE01TIN = null;
  private DecimalField fieldE01TIM = null;
  private DecimalField fieldE01TCO = null;
  private DecimalField fieldE01TIV = null;
  private CharacterField fieldE01CDE = null;
  private CharacterField fieldE01FON = null;
  private CharacterField fieldE01BDE = null;
  private CharacterField fieldE01ORD = null;
  private DecimalField fieldE01NDE = null;
  private DecimalField fieldE01REE = null;
  private CharacterField fieldE01USI = null;
  private DecimalField fieldE01FSI = null;
  private DecimalField fieldE01HSI = null;
  private DecimalField fieldE01FI1 = null;
  private DecimalField fieldE01FI2 = null;
  private CharacterField fieldE01FI3 = null;
  private CharacterField fieldE01FI4 = null;

  /**
  * Constructor for CRF000401Message.
  */
  public CRF000401Message()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
  protected void createFields()
  {
    recordsize = 510;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldH01USERID =
    new CharacterField(message, HEADERSIZE + 0, 10, "H01USERID");
    fields[1] = fieldH01PROGRM =
    new CharacterField(message, HEADERSIZE + 10, 10, "H01PROGRM");
    fields[2] = fieldH01TIMSYS =
    new CharacterField(message, HEADERSIZE + 20, 12, "H01TIMSYS");
    fields[3] = fieldH01SCRCOD =
    new CharacterField(message, HEADERSIZE + 32, 2, "H01SCRCOD");
    fields[4] = fieldH01OPECOD =
    new CharacterField(message, HEADERSIZE + 34, 4, "H01OPECOD");
    fields[5] = fieldH01FLGMAS =
    new CharacterField(message, HEADERSIZE + 38, 1, "H01FLGMAS");
    fields[6] = fieldH01FLGWK1 =
    new CharacterField(message, HEADERSIZE + 39, 1, "H01FLGWK1");
    fields[7] = fieldH01FLGWK2 =
    new CharacterField(message, HEADERSIZE + 40, 1, "H01FLGWK2");
    fields[8] = fieldH01FLGWK3 =
    new CharacterField(message, HEADERSIZE + 41, 1, "H01FLGWK3");
    fields[9] = fieldE01CSI =
    new DecimalField(message, HEADERSIZE + 42, 13, 0, "E01CSI");
    fields[10] = fieldE01CUN =
    new DecimalField(message, HEADERSIZE + 55, 10, 0, "E01CUN");
    fields[11] = fieldE01REF =
    new CharacterField(message, HEADERSIZE + 65, 13, "E01REF");
    fields[12] = fieldE01ACC =
    new DecimalField(message, HEADERSIZE + 78, 13, 0, "E01ACC");
    fields[13] = fieldE01AC1 =
    new DecimalField(message, HEADERSIZE + 91, 13, 0, "E01AC1");
    fields[14] = fieldE01BRN =
    new DecimalField(message, HEADERSIZE + 104, 4, 0, "E01BRN");
    fields[15] = fieldE01FAU =
    new DecimalField(message, HEADERSIZE + 108, 9, 0, "E01FAU");
    fields[16] = fieldE01FDE =
    new DecimalField(message, HEADERSIZE + 117, 9, 0, "E01FDE");
    fields[17] = fieldE01FA1 =
    new DecimalField(message, HEADERSIZE + 126, 9, 0, "E01FA1");
    fields[18] = fieldE01FA2 =
    new DecimalField(message, HEADERSIZE + 135, 9, 0, "E01FA2");
    fields[19] = fieldE01FVE =
    new DecimalField(message, HEADERSIZE + 144, 9, 0, "E01FVE");
    fields[20] = fieldE01VCU =
    new DecimalField(message, HEADERSIZE + 153, 16, 0, "E01VCU");
    fields[21] = fieldE01NCU =
    new DecimalField(message, HEADERSIZE + 169, 5, 0, "E01NCU");
    fields[22] = fieldE01FPA =
    new DecimalField(message, HEADERSIZE + 174, 4, 0, "E01FPA");
    fields[23] = fieldE01OAM =
    new DecimalField(message, HEADERSIZE + 178, 17, 2, "E01OAM");
    fields[24] = fieldE01MDE =
    new DecimalField(message, HEADERSIZE + 195, 17, 2, "E01MDE");
    fields[25] = fieldE01MSE =
    new DecimalField(message, HEADERSIZE + 212, 17, 2, "E01MSE");
    fields[26] = fieldE01MCS =
    new DecimalField(message, HEADERSIZE + 229, 17, 2, "E01MCS");
    fields[27] = fieldE01MIC =
    new DecimalField(message, HEADERSIZE + 246, 17, 2, "E01MIC");
    fields[28] = fieldE01RTE =
    new DecimalField(message, HEADERSIZE + 263, 11, 6, "E01RTE");
    fields[29] = fieldE01TIN =
    new DecimalField(message, HEADERSIZE + 274, 11, 6, "E01TIN");
    fields[30] = fieldE01TIM =
    new DecimalField(message, HEADERSIZE + 285, 11, 6, "E01TIM");
    fields[31] = fieldE01TCO =
    new DecimalField(message, HEADERSIZE + 296, 11, 6, "E01TCO");
    fields[32] = fieldE01TIV =
    new DecimalField(message, HEADERSIZE + 307, 7, 3, "E01TIV");
    fields[33] = fieldE01CDE =
    new CharacterField(message, HEADERSIZE + 314, 4, "E01CDE");
    fields[34] = fieldE01FON =
    new CharacterField(message, HEADERSIZE + 318, 4, "E01FON");
    fields[35] = fieldE01BDE =
    new CharacterField(message, HEADERSIZE + 322, 4, "E01BDE");
    fields[36] = fieldE01ORD =
    new CharacterField(message, HEADERSIZE + 326, 13, "E01ORD");
    fields[37] = fieldE01NDE =
    new DecimalField(message, HEADERSIZE + 339, 8, 0, "E01NDE");
    fields[38] = fieldE01REE =
    new DecimalField(message, HEADERSIZE + 347, 13, 0, "E01REE");
    fields[39] = fieldE01USI =
    new CharacterField(message, HEADERSIZE + 360, 20, "E01USI");
    fields[40] = fieldE01FSI =
    new DecimalField(message, HEADERSIZE + 380, 9, 0, "E01FSI");
    fields[41] = fieldE01HSI =
    new DecimalField(message, HEADERSIZE + 389, 7, 0, "E01HSI");
    fields[42] = fieldE01FI1 =
    new DecimalField(message, HEADERSIZE + 396, 17, 2, "E01FI1");
    fields[43] = fieldE01FI2 =
    new DecimalField(message, HEADERSIZE + 413, 17, 2, "E01FI2");
    fields[44] = fieldE01FI3 =
    new CharacterField(message, HEADERSIZE + 430, 40, "E01FI3");
    fields[45] = fieldE01FI4 =
    new CharacterField(message, HEADERSIZE + 470, 40, "E01FI4");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field H01USERID using a String value.
  */
  public void setH01USERID(String newvalue)
  {
    fieldH01USERID.setString(newvalue);
  }

  /**
  * Get value of field H01USERID as a String.
  */
  public String getH01USERID()
  {
    return fieldH01USERID.getString();
  }

  /**
  * Set field H01PROGRM using a String value.
  */
  public void setH01PROGRM(String newvalue)
  {
    fieldH01PROGRM.setString(newvalue);
  }

  /**
  * Get value of field H01PROGRM as a String.
  */
  public String getH01PROGRM()
  {
    return fieldH01PROGRM.getString();
  }

  /**
  * Set field H01TIMSYS using a String value.
  */
  public void setH01TIMSYS(String newvalue)
  {
    fieldH01TIMSYS.setString(newvalue);
  }

  /**
  * Get value of field H01TIMSYS as a String.
  */
  public String getH01TIMSYS()
  {
    return fieldH01TIMSYS.getString();
  }

  /**
  * Set field H01SCRCOD using a String value.
  */
  public void setH01SCRCOD(String newvalue)
  {
    fieldH01SCRCOD.setString(newvalue);
  }

  /**
  * Get value of field H01SCRCOD as a String.
  */
  public String getH01SCRCOD()
  {
    return fieldH01SCRCOD.getString();
  }

  /**
  * Set field H01OPECOD using a String value.
  */
  public void setH01OPECOD(String newvalue)
  {
    fieldH01OPECOD.setString(newvalue);
  }

  /**
  * Get value of field H01OPECOD as a String.
  */
  public String getH01OPECOD()
  {
    return fieldH01OPECOD.getString();
  }

  /**
  * Set field H01FLGMAS using a String value.
  */
  public void setH01FLGMAS(String newvalue)
  {
    fieldH01FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field H01FLGMAS as a String.
  */
  public String getH01FLGMAS()
  {
    return fieldH01FLGMAS.getString();
  }

  /**
  * Set field H01FLGWK1 using a String value.
  */
  public void setH01FLGWK1(String newvalue)
  {
    fieldH01FLGWK1.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK1 as a String.
  */
  public String getH01FLGWK1()
  {
    return fieldH01FLGWK1.getString();
  }

  /**
  * Set field H01FLGWK2 using a String value.
  */
  public void setH01FLGWK2(String newvalue)
  {
    fieldH01FLGWK2.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK2 as a String.
  */
  public String getH01FLGWK2()
  {
    return fieldH01FLGWK2.getString();
  }

  /**
  * Set field H01FLGWK3 using a String value.
  */
  public void setH01FLGWK3(String newvalue)
  {
    fieldH01FLGWK3.setString(newvalue);
  }

  /**
  * Get value of field H01FLGWK3 as a String.
  */
  public String getH01FLGWK3()
  {
    return fieldH01FLGWK3.getString();
  }

  /**
  * Set field E01CSI using a String value.
  */
  public void setE01CSI(String newvalue)
  {
    fieldE01CSI.setString(newvalue);
  }

  /**
  * Get value of field E01CSI as a String.
  */
  public String getE01CSI()
  {
    return fieldE01CSI.getString();
  }

  /**
  * Set numeric field E01CSI using a BigDecimal value.
  */
  public void setE01CSI(BigDecimal newvalue)
  {
    fieldE01CSI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CSI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CSI()
  {
    return fieldE01CSI.getBigDecimal();
  }

  /**
  * Set field E01CUN using a String value.
  */
  public void setE01CUN(String newvalue)
  {
    fieldE01CUN.setString(newvalue);
  }

  /**
  * Get value of field E01CUN as a String.
  */
  public String getE01CUN()
  {
    return fieldE01CUN.getString();
  }

  /**
  * Set numeric field E01CUN using a BigDecimal value.
  */
  public void setE01CUN(BigDecimal newvalue)
  {
    fieldE01CUN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01CUN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01CUN()
  {
    return fieldE01CUN.getBigDecimal();
  }

  /**
  * Set field E01REF using a String value.
  */
  public void setE01REF(String newvalue)
  {
    fieldE01REF.setString(newvalue);
  }

  /**
  * Get value of field E01REF as a String.
  */
  public String getE01REF()
  {
    return fieldE01REF.getString();
  }

  /**
  * Set field E01ACC using a String value.
  */
  public void setE01ACC(String newvalue)
  {
    fieldE01ACC.setString(newvalue);
  }

  /**
  * Get value of field E01ACC as a String.
  */
  public String getE01ACC()
  {
    return fieldE01ACC.getString();
  }

  /**
  * Set numeric field E01ACC using a BigDecimal value.
  */
  public void setE01ACC(BigDecimal newvalue)
  {
    fieldE01ACC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01ACC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01ACC()
  {
    return fieldE01ACC.getBigDecimal();
  }

  /**
  * Set field E01AC1 using a String value.
  */
  public void setE01AC1(String newvalue)
  {
    fieldE01AC1.setString(newvalue);
  }

  /**
  * Get value of field E01AC1 as a String.
  */
  public String getE01AC1()
  {
    return fieldE01AC1.getString();
  }

  /**
  * Set numeric field E01AC1 using a BigDecimal value.
  */
  public void setE01AC1(BigDecimal newvalue)
  {
    fieldE01AC1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01AC1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01AC1()
  {
    return fieldE01AC1.getBigDecimal();
  }

  /**
  * Set field E01BRN using a String value.
  */
  public void setE01BRN(String newvalue)
  {
    fieldE01BRN.setString(newvalue);
  }

  /**
  * Get value of field E01BRN as a String.
  */
  public String getE01BRN()
  {
    return fieldE01BRN.getString();
  }

  /**
  * Set numeric field E01BRN using a BigDecimal value.
  */
  public void setE01BRN(BigDecimal newvalue)
  {
    fieldE01BRN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01BRN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01BRN()
  {
    return fieldE01BRN.getBigDecimal();
  }

  /**
  * Set field E01FAU using a String value.
  */
  public void setE01FAU(String newvalue)
  {
    fieldE01FAU.setString(newvalue);
  }

  /**
  * Get value of field E01FAU as a String.
  */
  public String getE01FAU()
  {
    return fieldE01FAU.getString();
  }

  /**
  * Set numeric field E01FAU using a BigDecimal value.
  */
  public void setE01FAU(BigDecimal newvalue)
  {
    fieldE01FAU.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FAU as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FAU()
  {
    return fieldE01FAU.getBigDecimal();
  }

  /**
  * Set field E01FDE using a String value.
  */
  public void setE01FDE(String newvalue)
  {
    fieldE01FDE.setString(newvalue);
  }

  /**
  * Get value of field E01FDE as a String.
  */
  public String getE01FDE()
  {
    return fieldE01FDE.getString();
  }

  /**
  * Set numeric field E01FDE using a BigDecimal value.
  */
  public void setE01FDE(BigDecimal newvalue)
  {
    fieldE01FDE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FDE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FDE()
  {
    return fieldE01FDE.getBigDecimal();
  }

  /**
  * Set field E01FA1 using a String value.
  */
  public void setE01FA1(String newvalue)
  {
    fieldE01FA1.setString(newvalue);
  }

  /**
  * Get value of field E01FA1 as a String.
  */
  public String getE01FA1()
  {
    return fieldE01FA1.getString();
  }

  /**
  * Set numeric field E01FA1 using a BigDecimal value.
  */
  public void setE01FA1(BigDecimal newvalue)
  {
    fieldE01FA1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FA1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FA1()
  {
    return fieldE01FA1.getBigDecimal();
  }

  /**
  * Set field E01FA2 using a String value.
  */
  public void setE01FA2(String newvalue)
  {
    fieldE01FA2.setString(newvalue);
  }

  /**
  * Get value of field E01FA2 as a String.
  */
  public String getE01FA2()
  {
    return fieldE01FA2.getString();
  }

  /**
  * Set numeric field E01FA2 using a BigDecimal value.
  */
  public void setE01FA2(BigDecimal newvalue)
  {
    fieldE01FA2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FA2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FA2()
  {
    return fieldE01FA2.getBigDecimal();
  }

  /**
  * Set field E01FVE using a String value.
  */
  public void setE01FVE(String newvalue)
  {
    fieldE01FVE.setString(newvalue);
  }

  /**
  * Get value of field E01FVE as a String.
  */
  public String getE01FVE()
  {
    return fieldE01FVE.getString();
  }

  /**
  * Set numeric field E01FVE using a BigDecimal value.
  */
  public void setE01FVE(BigDecimal newvalue)
  {
    fieldE01FVE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FVE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FVE()
  {
    return fieldE01FVE.getBigDecimal();
  }

  /**
  * Set field E01VCU using a String value.
  */
  public void setE01VCU(String newvalue)
  {
    fieldE01VCU.setString(newvalue);
  }

  /**
  * Get value of field E01VCU as a String.
  */
  public String getE01VCU()
  {
    return fieldE01VCU.getString();
  }

  /**
  * Set numeric field E01VCU using a BigDecimal value.
  */
  public void setE01VCU(BigDecimal newvalue)
  {
    fieldE01VCU.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01VCU as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01VCU()
  {
    return fieldE01VCU.getBigDecimal();
  }

  /**
  * Set field E01NCU using a String value.
  */
  public void setE01NCU(String newvalue)
  {
    fieldE01NCU.setString(newvalue);
  }

  /**
  * Get value of field E01NCU as a String.
  */
  public String getE01NCU()
  {
    return fieldE01NCU.getString();
  }

  /**
  * Set numeric field E01NCU using a BigDecimal value.
  */
  public void setE01NCU(BigDecimal newvalue)
  {
    fieldE01NCU.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01NCU as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01NCU()
  {
    return fieldE01NCU.getBigDecimal();
  }

  /**
  * Set field E01FPA using a String value.
  */
  public void setE01FPA(String newvalue)
  {
    fieldE01FPA.setString(newvalue);
  }

  /**
  * Get value of field E01FPA as a String.
  */
  public String getE01FPA()
  {
    return fieldE01FPA.getString();
  }

  /**
  * Set numeric field E01FPA using a BigDecimal value.
  */
  public void setE01FPA(BigDecimal newvalue)
  {
    fieldE01FPA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FPA as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FPA()
  {
    return fieldE01FPA.getBigDecimal();
  }

  /**
  * Set field E01OAM using a String value.
  */
  public void setE01OAM(String newvalue)
  {
    fieldE01OAM.setString(newvalue);
  }

  /**
  * Get value of field E01OAM as a String.
  */
  public String getE01OAM()
  {
    return fieldE01OAM.getString();
  }

  /**
  * Set numeric field E01OAM using a BigDecimal value.
  */
  public void setE01OAM(BigDecimal newvalue)
  {
    fieldE01OAM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01OAM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01OAM()
  {
    return fieldE01OAM.getBigDecimal();
  }

  /**
  * Set field E01MDE using a String value.
  */
  public void setE01MDE(String newvalue)
  {
    fieldE01MDE.setString(newvalue);
  }

  /**
  * Get value of field E01MDE as a String.
  */
  public String getE01MDE()
  {
    return fieldE01MDE.getString();
  }

  /**
  * Set numeric field E01MDE using a BigDecimal value.
  */
  public void setE01MDE(BigDecimal newvalue)
  {
    fieldE01MDE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01MDE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01MDE()
  {
    return fieldE01MDE.getBigDecimal();
  }

  /**
  * Set field E01MSE using a String value.
  */
  public void setE01MSE(String newvalue)
  {
    fieldE01MSE.setString(newvalue);
  }

  /**
  * Get value of field E01MSE as a String.
  */
  public String getE01MSE()
  {
    return fieldE01MSE.getString();
  }

  /**
  * Set numeric field E01MSE using a BigDecimal value.
  */
  public void setE01MSE(BigDecimal newvalue)
  {
    fieldE01MSE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01MSE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01MSE()
  {
    return fieldE01MSE.getBigDecimal();
  }

  /**
  * Set field E01MCS using a String value.
  */
  public void setE01MCS(String newvalue)
  {
    fieldE01MCS.setString(newvalue);
  }

  /**
  * Get value of field E01MCS as a String.
  */
  public String getE01MCS()
  {
    return fieldE01MCS.getString();
  }

  /**
  * Set numeric field E01MCS using a BigDecimal value.
  */
  public void setE01MCS(BigDecimal newvalue)
  {
    fieldE01MCS.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01MCS as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01MCS()
  {
    return fieldE01MCS.getBigDecimal();
  }

  /**
  * Set field E01MIC using a String value.
  */
  public void setE01MIC(String newvalue)
  {
    fieldE01MIC.setString(newvalue);
  }

  /**
  * Get value of field E01MIC as a String.
  */
  public String getE01MIC()
  {
    return fieldE01MIC.getString();
  }

  /**
  * Set numeric field E01MIC using a BigDecimal value.
  */
  public void setE01MIC(BigDecimal newvalue)
  {
    fieldE01MIC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01MIC as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01MIC()
  {
    return fieldE01MIC.getBigDecimal();
  }

  /**
  * Set field E01RTE using a String value.
  */
  public void setE01RTE(String newvalue)
  {
    fieldE01RTE.setString(newvalue);
  }

  /**
  * Get value of field E01RTE as a String.
  */
  public String getE01RTE()
  {
    return fieldE01RTE.getString();
  }

  /**
  * Set numeric field E01RTE using a BigDecimal value.
  */
  public void setE01RTE(BigDecimal newvalue)
  {
    fieldE01RTE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01RTE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01RTE()
  {
    return fieldE01RTE.getBigDecimal();
  }

  /**
  * Set field E01TIN using a String value.
  */
  public void setE01TIN(String newvalue)
  {
    fieldE01TIN.setString(newvalue);
  }

  /**
  * Get value of field E01TIN as a String.
  */
  public String getE01TIN()
  {
    return fieldE01TIN.getString();
  }

  /**
  * Set numeric field E01TIN using a BigDecimal value.
  */
  public void setE01TIN(BigDecimal newvalue)
  {
    fieldE01TIN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TIN as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TIN()
  {
    return fieldE01TIN.getBigDecimal();
  }

  /**
  * Set field E01TIM using a String value.
  */
  public void setE01TIM(String newvalue)
  {
    fieldE01TIM.setString(newvalue);
  }

  /**
  * Get value of field E01TIM as a String.
  */
  public String getE01TIM()
  {
    return fieldE01TIM.getString();
  }

  /**
  * Set numeric field E01TIM using a BigDecimal value.
  */
  public void setE01TIM(BigDecimal newvalue)
  {
    fieldE01TIM.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TIM as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TIM()
  {
    return fieldE01TIM.getBigDecimal();
  }

  /**
  * Set field E01TCO using a String value.
  */
  public void setE01TCO(String newvalue)
  {
    fieldE01TCO.setString(newvalue);
  }

  /**
  * Get value of field E01TCO as a String.
  */
  public String getE01TCO()
  {
    return fieldE01TCO.getString();
  }

  /**
  * Set numeric field E01TCO using a BigDecimal value.
  */
  public void setE01TCO(BigDecimal newvalue)
  {
    fieldE01TCO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TCO as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TCO()
  {
    return fieldE01TCO.getBigDecimal();
  }

  /**
  * Set field E01TIV using a String value.
  */
  public void setE01TIV(String newvalue)
  {
    fieldE01TIV.setString(newvalue);
  }

  /**
  * Get value of field E01TIV as a String.
  */
  public String getE01TIV()
  {
    return fieldE01TIV.getString();
  }

  /**
  * Set numeric field E01TIV using a BigDecimal value.
  */
  public void setE01TIV(BigDecimal newvalue)
  {
    fieldE01TIV.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01TIV as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01TIV()
  {
    return fieldE01TIV.getBigDecimal();
  }

  /**
  * Set field E01CDE using a String value.
  */
  public void setE01CDE(String newvalue)
  {
    fieldE01CDE.setString(newvalue);
  }

  /**
  * Get value of field E01CDE as a String.
  */
  public String getE01CDE()
  {
    return fieldE01CDE.getString();
  }

  /**
  * Set field E01FON using a String value.
  */
  public void setE01FON(String newvalue)
  {
    fieldE01FON.setString(newvalue);
  }

  /**
  * Get value of field E01FON as a String.
  */
  public String getE01FON()
  {
    return fieldE01FON.getString();
  }

  /**
  * Set field E01BDE using a String value.
  */
  public void setE01BDE(String newvalue)
  {
    fieldE01BDE.setString(newvalue);
  }

  /**
  * Get value of field E01BDE as a String.
  */
  public String getE01BDE()
  {
    return fieldE01BDE.getString();
  }

  /**
  * Set field E01ORD using a String value.
  */
  public void setE01ORD(String newvalue)
  {
    fieldE01ORD.setString(newvalue);
  }

  /**
  * Get value of field E01ORD as a String.
  */
  public String getE01ORD()
  {
    return fieldE01ORD.getString();
  }

  /**
  * Set field E01NDE using a String value.
  */
  public void setE01NDE(String newvalue)
  {
    fieldE01NDE.setString(newvalue);
  }

  /**
  * Get value of field E01NDE as a String.
  */
  public String getE01NDE()
  {
    return fieldE01NDE.getString();
  }

  /**
  * Set numeric field E01NDE using a BigDecimal value.
  */
  public void setE01NDE(BigDecimal newvalue)
  {
    fieldE01NDE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01NDE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01NDE()
  {
    return fieldE01NDE.getBigDecimal();
  }

  /**
  * Set field E01REE using a String value.
  */
  public void setE01REE(String newvalue)
  {
    fieldE01REE.setString(newvalue);
  }

  /**
  * Get value of field E01REE as a String.
  */
  public String getE01REE()
  {
    return fieldE01REE.getString();
  }

  /**
  * Set numeric field E01REE using a BigDecimal value.
  */
  public void setE01REE(BigDecimal newvalue)
  {
    fieldE01REE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01REE as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01REE()
  {
    return fieldE01REE.getBigDecimal();
  }

  /**
  * Set field E01USI using a String value.
  */
  public void setE01USI(String newvalue)
  {
    fieldE01USI.setString(newvalue);
  }

  /**
  * Get value of field E01USI as a String.
  */
  public String getE01USI()
  {
    return fieldE01USI.getString();
  }

  /**
  * Set field E01FSI using a String value.
  */
  public void setE01FSI(String newvalue)
  {
    fieldE01FSI.setString(newvalue);
  }

  /**
  * Get value of field E01FSI as a String.
  */
  public String getE01FSI()
  {
    return fieldE01FSI.getString();
  }

  /**
  * Set numeric field E01FSI using a BigDecimal value.
  */
  public void setE01FSI(BigDecimal newvalue)
  {
    fieldE01FSI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FSI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FSI()
  {
    return fieldE01FSI.getBigDecimal();
  }

  /**
  * Set field E01HSI using a String value.
  */
  public void setE01HSI(String newvalue)
  {
    fieldE01HSI.setString(newvalue);
  }

  /**
  * Get value of field E01HSI as a String.
  */
  public String getE01HSI()
  {
    return fieldE01HSI.getString();
  }

  /**
  * Set numeric field E01HSI using a BigDecimal value.
  */
  public void setE01HSI(BigDecimal newvalue)
  {
    fieldE01HSI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01HSI as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01HSI()
  {
    return fieldE01HSI.getBigDecimal();
  }

  /**
  * Set field E01FI1 using a String value.
  */
  public void setE01FI1(String newvalue)
  {
    fieldE01FI1.setString(newvalue);
  }

  /**
  * Get value of field E01FI1 as a String.
  */
  public String getE01FI1()
  {
    return fieldE01FI1.getString();
  }

  /**
  * Set numeric field E01FI1 using a BigDecimal value.
  */
  public void setE01FI1(BigDecimal newvalue)
  {
    fieldE01FI1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FI1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FI1()
  {
    return fieldE01FI1.getBigDecimal();
  }

  /**
  * Set field E01FI2 using a String value.
  */
  public void setE01FI2(String newvalue)
  {
    fieldE01FI2.setString(newvalue);
  }

  /**
  * Get value of field E01FI2 as a String.
  */
  public String getE01FI2()
  {
    return fieldE01FI2.getString();
  }

  /**
  * Set numeric field E01FI2 using a BigDecimal value.
  */
  public void setE01FI2(BigDecimal newvalue)
  {
    fieldE01FI2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field E01FI2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalE01FI2()
  {
    return fieldE01FI2.getBigDecimal();
  }

  /**
  * Set field E01FI3 using a String value.
  */
  public void setE01FI3(String newvalue)
  {
    fieldE01FI3.setString(newvalue);
  }

  /**
  * Get value of field E01FI3 as a String.
  */
  public String getE01FI3()
  {
    return fieldE01FI3.getString();
  }

  /**
  * Set field E01FI4 using a String value.
  */
  public void setE01FI4(String newvalue)
  {
    fieldE01FI4.setString(newvalue);
  }

  /**
  * Get value of field E01FI4 as a String.
  */
  public String getE01FI4()
  {
    return fieldE01FI4.getString();
  }

}
